# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/clubsports',
                'doc_host': 'https://aliceheiman.github.io',
                'git_url': 'https://github.com/aliceheiman/clubsports',
                'lib_path': 'clubsports'},
  'syms': {'clubsports.core': {'clubsports.core.foo': ('core.html#foo', 'clubsports/core.py')}}}
